name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      Environnement:
        description: 'The environment i need to deploy on'
        required: true
        default: '/dev'

jobs:
  manual-job:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Example
        run: |
          echo "Mon exemple"
          echo "Env Name: ${{ github.event.inputs.Environnement }}"
      - name: Github variable
        run: |
          echo 'Affichage des variables Github :'
          echo '${{ toJSON(github) }}' | jq .
      - name: Runner Variable
        run: |
          echo 'Affichage des variables Runner :'
          echo '${{ toJSON(runner) }}' | jq .
      - name: Secrets variable
        run: |
          echo 'Affichage des secrets :'
          echo '${{ toJSON(secrets) }}'
      - name: Custom Variable (MY_API_URL)
        run: |
          echo 'Affichage de la variable MY_API_URL :'
          echo '${{ vars.MY_API_URL }}'
